<?php

function es_site_announcement_page_attachments(array &$page) {

    $module_key = 'es_site_announcement';

    $module_config = \Drupal::config("{$module_key}.settings")->get();

    if ( $module_config ) {
        $page['#attached']['drupalSettings'][$module_key] = $module_config;
    }

    $route = \Drupal::routeMatch()->getRouteObject();
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);    

    if ( !$is_admin ) {
        $page['#attached']['library'][] = 'es_site_announcement/es_site_announcement';
    }
    
}